insert into app_settings (key, value)
values
  ('system', '{"banner":"Base da Copa 2026 carregada com sele??es, grupos e jogos oficiais.","bonus_lock_at":"2026-06-11T17:30:00.000Z","zebra_tournament_options":[{"group":"A","team":"?frica do Sul"},{"group":"B","team":"B?snia e Herzegovina"},{"group":"C","team":"Haiti"},{"group":"D","team":"Austr?lia"},{"group":"E","team":"Cura?ao"},{"group":"F","team":"Tun?sia"},{"group":"G","team":"Nova Zel?ndia"},{"group":"H","team":"Cabo Verde"},{"group":"I","team":"Iraque"},{"group":"J","team":"Jord?nia"},{"group":"K","team":"Congo DR"},{"group":"L","team":"Panam?"}]}'::jsonb)
on conflict (key)
do update set value = excluded.value, updated_at = now();

insert into matches (
  id, match_number, phase, phase_label, group_name, home_team, away_team, home_code, away_code, starts_at, stadium, location, status, score_home, score_away, extra_time_home, extra_time_away, winner_team
)
values
  ('group-A-1', 1, 'group', 'Grupo A', 'A', 'México', 'África do Sul', 'MEX', 'RSA', '2026-06-11T18:00:00Z', 'Estádio da Cidade do México', 'Cidade do México', 'scheduled', null, null, null, null, null),
  ('group-A-2', 2, 'group', 'Grupo A', 'A', 'Coreia do Sul', 'Tchéquia', 'KOR', 'CZE', '2026-06-11T22:00:00Z', 'Estádio Guadalajara', 'Guadalajara', 'scheduled', null, null, null, null, null),
  ('group-B-1', 3, 'group', 'Grupo B', 'B', 'Canadá', 'Bósnia e Herzegovina', 'CAN', 'BIH', '2026-06-12T18:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('group-D-1', 4, 'group', 'Grupo D', 'D', 'Estados Unidos', 'Paraguai', 'USA', 'PAR', '2026-06-12T22:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('group-C-1', 5, 'group', 'Grupo C', 'C', 'Haiti', 'Escócia', 'HAI', 'SCO', '2026-06-13T16:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('group-D-2', 6, 'group', 'Grupo D', 'D', 'Austrália', 'Turquia', 'AUS', 'TUR', '2026-06-13T19:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('group-C-2', 7, 'group', 'Grupo C', 'C', 'Brasil', 'Marrocos', 'BRA', 'MAR', '2026-06-13T22:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('group-B-2', 8, 'group', 'Grupo B', 'B', 'Catar', 'Suíça', 'QAT', 'SUI', '2026-06-13T23:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('group-E-1', 9, 'group', 'Grupo E', 'E', 'Costa do Marfim', 'Equador', 'CIV', 'ECU', '2026-06-14T16:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('group-E-2', 10, 'group', 'Grupo E', 'E', 'Alemanha', 'Curaçao', 'GER', 'CUW', '2026-06-14T20:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('group-F-1', 11, 'group', 'Grupo F', 'F', 'Holanda', 'Japão', 'NED', 'JPN', '2026-06-14T22:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('group-F-2', 12, 'group', 'Grupo F', 'F', 'Suécia', 'Tunísia', 'SWE', 'TUN', '2026-06-14T23:00:00Z', 'Estádio Monterrey', 'Monterrey', 'scheduled', null, null, null, null, null),
  ('group-H-1', 13, 'group', 'Grupo H', 'H', 'Arábia Saudita', 'Uruguai', 'KSA', 'URU', '2026-06-15T16:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('group-H-2', 14, 'group', 'Grupo H', 'H', 'Espanha', 'Cabo Verde', 'ESP', 'CPV', '2026-06-15T19:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('group-G-1', 15, 'group', 'Grupo G', 'G', 'Irã', 'Nova Zelândia', 'IRN', 'NZL', '2026-06-15T22:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('group-G-2', 16, 'group', 'Grupo G', 'G', 'Bélgica', 'Egito', 'BEL', 'EGY', '2026-06-15T23:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('group-I-1', 17, 'group', 'Grupo I', 'I', 'França', 'Senegal', 'FRA', 'SEN', '2026-06-16T18:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('group-I-2', 18, 'group', 'Grupo I', 'I', 'Iraque', 'Noruega', 'IRQ', 'NOR', '2026-06-16T22:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('group-J-1', 19, 'group', 'Grupo J', 'J', 'Argentina', 'Argélia', 'ARG', 'ALG', '2026-06-16T23:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('group-J-2', 20, 'group', 'Grupo J', 'J', 'Áustria', 'Jordânia', 'AUT', 'JOR', '2026-06-17T01:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('group-L-1', 21, 'group', 'Grupo L', 'L', 'Gana', 'Panamá', 'GHA', 'PAN', '2026-06-17T18:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('group-L-2', 22, 'group', 'Grupo L', 'L', 'Inglaterra', 'Croácia', 'ENG', 'CRO', '2026-06-17T22:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('group-K-1', 23, 'group', 'Grupo K', 'K', 'Portugal', 'Congo DR', 'POR', 'COD', '2026-06-17T23:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('group-K-2', 24, 'group', 'Grupo K', 'K', 'Uzbequistão', 'Colômbia', 'UZB', 'COL', '2026-06-18T01:00:00Z', 'Estádio da Cidade do México', 'Cidade do México', 'scheduled', null, null, null, null, null),
  ('group-A-3', 25, 'group', 'Grupo A', 'A', 'Tchéquia', 'África do Sul', 'CZE', 'RSA', '2026-06-18T18:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('group-B-3', 26, 'group', 'Grupo B', 'B', 'Suíça', 'Bósnia e Herzegovina', 'SUI', 'BIH', '2026-06-18T19:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('group-B-4', 27, 'group', 'Grupo B', 'B', 'Canadá', 'Catar', 'CAN', 'QAT', '2026-06-18T22:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('group-A-4', 28, 'group', 'Grupo A', 'A', 'México', 'Coreia do Sul', 'MEX', 'KOR', '2026-06-18T23:00:00Z', 'Estádio Guadalajara', 'Guadalajara', 'scheduled', null, null, null, null, null),
  ('group-C-3', 29, 'group', 'Grupo C', 'C', 'Brasil', 'Haiti', 'BRA', 'HAI', '2026-06-19T18:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('group-C-4', 30, 'group', 'Grupo C', 'C', 'Escócia', 'Marrocos', 'SCO', 'MAR', '2026-06-19T22:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('group-D-3', 31, 'group', 'Grupo D', 'D', 'Turquia', 'Paraguai', 'TUR', 'PAR', '2026-06-19T23:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('group-D-4', 32, 'group', 'Grupo D', 'D', 'Estados Unidos', 'Austrália', 'USA', 'AUS', '2026-06-20T01:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('group-E-3', 33, 'group', 'Grupo E', 'E', 'Alemanha', 'Costa do Marfim', 'GER', 'CIV', '2026-06-20T18:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('group-E-4', 34, 'group', 'Grupo E', 'E', 'Equador', 'Curaçao', 'ECU', 'CUW', '2026-06-20T22:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('group-F-3', 35, 'group', 'Grupo F', 'F', 'Holanda', 'Suécia', 'NED', 'SWE', '2026-06-20T23:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('group-F-4', 36, 'group', 'Grupo F', 'F', 'Tunísia', 'Japão', 'TUN', 'JPN', '2026-06-21T01:00:00Z', 'Estádio Monterrey', 'Monterrey', 'scheduled', null, null, null, null, null),
  ('group-H-3', 37, 'group', 'Grupo H', 'H', 'Uruguai', 'Cabo Verde', 'URU', 'CPV', '2026-06-21T18:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('group-H-4', 38, 'group', 'Grupo H', 'H', 'Espanha', 'Arábia Saudita', 'ESP', 'KSA', '2026-06-21T22:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('group-G-3', 39, 'group', 'Grupo G', 'G', 'Bélgica', 'Irã', 'BEL', 'IRN', '2026-06-21T23:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('group-G-4', 40, 'group', 'Grupo G', 'G', 'Nova Zelândia', 'Egito', 'NZL', 'EGY', '2026-06-22T01:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('group-I-3', 41, 'group', 'Grupo I', 'I', 'Noruega', 'Senegal', 'NOR', 'SEN', '2026-06-22T18:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('group-I-4', 42, 'group', 'Grupo I', 'I', 'França', 'Iraque', 'FRA', 'IRQ', '2026-06-22T22:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('group-J-3', 43, 'group', 'Grupo J', 'J', 'Argentina', 'Áustria', 'ARG', 'AUT', '2026-06-22T23:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('group-J-4', 44, 'group', 'Grupo J', 'J', 'Jordânia', 'Argélia', 'JOR', 'ALG', '2026-06-23T01:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('group-L-3', 45, 'group', 'Grupo L', 'L', 'Inglaterra', 'Gana', 'ENG', 'GHA', '2026-06-23T18:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('group-L-4', 46, 'group', 'Grupo L', 'L', 'Panamá', 'Croácia', 'PAN', 'CRO', '2026-06-23T22:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('group-K-3', 47, 'group', 'Grupo K', 'K', 'Portugal', 'Uzbequistão', 'POR', 'UZB', '2026-06-23T23:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('group-K-4', 48, 'group', 'Grupo K', 'K', 'Colômbia', 'Congo DR', 'COL', 'COD', '2026-06-24T01:00:00Z', 'Estádio Guadalajara', 'Guadalajara', 'scheduled', null, null, null, null, null),
  ('group-C-5', 49, 'group', 'Grupo C', 'C', 'Escócia', 'Brasil', 'SCO', 'BRA', '2026-06-24T18:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('group-C-6', 50, 'group', 'Grupo C', 'C', 'Marrocos', 'Haiti', 'MAR', 'HAI', '2026-06-24T22:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('group-B-5', 51, 'group', 'Grupo B', 'B', 'Suíça', 'Canadá', 'SUI', 'CAN', '2026-06-24T23:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('group-B-6', 52, 'group', 'Grupo B', 'B', 'Bósnia e Herzegovina', 'Catar', 'BIH', 'QAT', '2026-06-25T01:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('group-A-5', 53, 'group', 'Grupo A', 'A', 'Tchéquia', 'México', 'CZE', 'MEX', '2026-06-25T02:00:00Z', 'Estádio da Cidade do México', 'Cidade do México', 'scheduled', null, null, null, null, null),
  ('group-A-6', 54, 'group', 'Grupo A', 'A', 'África do Sul', 'Coreia do Sul', 'RSA', 'KOR', '2026-06-25T02:00:00Z', 'Estádio Monterrey', 'Monterrey', 'scheduled', null, null, null, null, null),
  ('group-E-5', 55, 'group', 'Grupo E', 'E', 'Curaçao', 'Costa do Marfim', 'CUW', 'CIV', '2026-06-25T18:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('group-E-6', 56, 'group', 'Grupo E', 'E', 'Equador', 'Alemanha', 'ECU', 'GER', '2026-06-25T22:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('group-F-5', 57, 'group', 'Grupo F', 'F', 'Japão', 'Suécia', 'JPN', 'SWE', '2026-06-25T23:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('group-F-6', 58, 'group', 'Grupo F', 'F', 'Tunísia', 'Holanda', 'TUN', 'NED', '2026-06-26T01:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('group-D-5', 59, 'group', 'Grupo D', 'D', 'Turquia', 'Estados Unidos', 'TUR', 'USA', '2026-06-25T23:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('group-D-6', 60, 'group', 'Grupo D', 'D', 'Paraguai', 'Austrália', 'PAR', 'AUS', '2026-06-26T01:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('group-I-5', 61, 'group', 'Grupo I', 'I', 'Noruega', 'França', 'NOR', 'FRA', '2026-06-26T18:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('group-I-6', 62, 'group', 'Grupo I', 'I', 'Senegal', 'Iraque', 'SEN', 'IRQ', '2026-06-26T22:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('group-G-5', 63, 'group', 'Grupo G', 'G', 'Egito', 'Irã', 'EGY', 'IRN', '2026-06-26T23:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('group-G-6', 64, 'group', 'Grupo G', 'G', 'Nova Zelândia', 'Bélgica', 'NZL', 'BEL', '2026-06-27T01:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('group-H-5', 65, 'group', 'Grupo H', 'H', 'Cabo Verde', 'Arábia Saudita', 'CPV', 'KSA', '2026-06-26T23:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('group-H-6', 66, 'group', 'Grupo H', 'H', 'Uruguai', 'Espanha', 'URU', 'ESP', '2026-06-27T01:00:00Z', 'Estádio Guadalajara', 'Guadalajara', 'scheduled', null, null, null, null, null),
  ('group-L-5', 67, 'group', 'Grupo L', 'L', 'Panamá', 'Inglaterra', 'PAN', 'ENG', '2026-06-27T18:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('group-L-6', 68, 'group', 'Grupo L', 'L', 'Croácia', 'Gana', 'CRO', 'GHA', '2026-06-27T22:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('group-J-5', 69, 'group', 'Grupo J', 'J', 'Argélia', 'Áustria', 'ALG', 'AUT', '2026-06-27T23:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('group-J-6', 70, 'group', 'Grupo J', 'J', 'Jordânia', 'Argentina', 'JOR', 'ARG', '2026-06-28T01:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('group-K-5', 71, 'group', 'Grupo K', 'K', 'Colômbia', 'Portugal', 'COL', 'POR', '2026-06-27T23:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('group-K-6', 72, 'group', 'Grupo K', 'K', 'Congo DR', 'Uzbequistão', 'COD', 'UZB', '2026-06-28T01:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('round32-1', 73, 'round32', '16 avos de final', null, '2º do Grupo A', '2º do Grupo B', '2º do Grupo A', '2º do Grupo B', '2026-06-28T20:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('round32-2', 74, 'round32', '16 avos de final', null, '1º do Grupo E', 'Melhor 3º colocado', '1º do Grupo E', 'Melhor 3º colocado', '2026-06-29T18:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('round32-3', 75, 'round32', '16 avos de final', null, '1º do Grupo F', '2º do Grupo C', '1º do Grupo F', '2º do Grupo C', '2026-06-29T22:00:00Z', 'Estádio Monterrey', 'Monterrey', 'scheduled', null, null, null, null, null),
  ('round32-4', 76, 'round32', '16 avos de final', null, '1º do Grupo C', '2º do Grupo F', '1º do Grupo C', '2º do Grupo F', '2026-06-30T01:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('round32-5', 77, 'round32', '16 avos de final', null, '1º do Grupo I', 'Melhor 3º colocado', '1º do Grupo I', 'Melhor 3º colocado', '2026-06-30T18:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('round32-6', 78, 'round32', '16 avos de final', null, '2º do Grupo E', '2º do Grupo I', '2º do Grupo E', '2º do Grupo I', '2026-06-30T22:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('round32-7', 79, 'round32', '16 avos de final', null, '1º do Grupo A', 'Melhor 3º colocado', '1º do Grupo A', 'Melhor 3º colocado', '2026-07-01T01:00:00Z', 'Estádio da Cidade do México', 'Cidade do México', 'scheduled', null, null, null, null, null),
  ('round32-8', 80, 'round32', '16 avos de final', null, '1º do Grupo L', 'Melhor 3º colocado', '1º do Grupo L', 'Melhor 3º colocado', '2026-07-01T18:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('round32-9', 81, 'round32', '16 avos de final', null, '1º do Grupo D', 'Melhor 3º colocado', '1º do Grupo D', 'Melhor 3º colocado', '2026-07-01T22:00:00Z', 'Estádio da Baía de São Francisco', 'São Francisco', 'scheduled', null, null, null, null, null),
  ('round32-10', 82, 'round32', '16 avos de final', null, '1º do Grupo G', 'Melhor 3º colocado', '1º do Grupo G', 'Melhor 3º colocado', '2026-07-02T01:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('round32-11', 83, 'round32', '16 avos de final', null, '2º do Grupo K', '2º do Grupo L', '2º do Grupo K', '2º do Grupo L', '2026-07-02T18:00:00Z', 'Estádio de Toronto', 'Toronto', 'scheduled', null, null, null, null, null),
  ('round32-12', 84, 'round32', '16 avos de final', null, '1º do Grupo H', '2º do Grupo J', '1º do Grupo H', '2º do Grupo J', '2026-07-02T22:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('round32-13', 85, 'round32', '16 avos de final', null, '1º do Grupo B', 'Melhor 3º colocado', '1º do Grupo B', 'Melhor 3º colocado', '2026-07-03T01:00:00Z', 'BC Place Vancouver', 'Vancouver', 'scheduled', null, null, null, null, null),
  ('round32-14', 86, 'round32', '16 avos de final', null, '1º do Grupo J', '2º do Grupo H', '1º do Grupo J', '2º do Grupo H', '2026-07-03T18:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('round32-15', 87, 'round32', '16 avos de final', null, '1º do Grupo K', 'Melhor 3º colocado', '1º do Grupo K', 'Melhor 3º colocado', '2026-07-03T22:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('round32-16', 88, 'round32', '16 avos de final', null, '2º do Grupo D', '2º do Grupo G', '2º do Grupo D', '2º do Grupo G', '2026-07-04T01:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('round16-1', 89, 'round16', 'Oitavas', null, 'Vencedor J74', 'Vencedor J77', 'Vencedor J74', 'Vencedor J77', '2026-07-04T18:00:00Z', 'Estádio da Filadélfia', 'Filadélfia', 'scheduled', null, null, null, null, null),
  ('round16-2', 90, 'round16', 'Oitavas', null, 'Vencedor J73', 'Vencedor J75', 'Vencedor J73', 'Vencedor J75', '2026-07-04T22:00:00Z', 'Estádio de Houston', 'Houston', 'scheduled', null, null, null, null, null),
  ('round16-3', 91, 'round16', 'Oitavas', null, 'Vencedor J76', 'Vencedor J78', 'Vencedor J76', 'Vencedor J78', '2026-07-05T18:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('round16-4', 92, 'round16', 'Oitavas', null, 'Vencedor J79', 'Vencedor J82', 'Vencedor J79', 'Vencedor J82', '2026-07-05T22:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('round16-5', 93, 'round16', 'Oitavas', null, 'Vencedor J80', 'Vencedor J84', 'Vencedor J80', 'Vencedor J84', '2026-07-06T18:00:00Z', 'Estádio de Seattle', 'Seattle', 'scheduled', null, null, null, null, null),
  ('round16-6', 94, 'round16', 'Oitavas', null, 'Vencedor J81', 'Vencedor J86', 'Vencedor J81', 'Vencedor J86', '2026-07-06T22:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('round16-7', 95, 'round16', 'Oitavas', null, 'Vencedor J83', 'Vencedor J87', 'Vencedor J83', 'Vencedor J87', '2026-07-07T18:00:00Z', 'Estádio da Cidade do México', 'Cidade do México', 'scheduled', null, null, null, null, null),
  ('round16-8', 96, 'round16', 'Oitavas', null, 'Vencedor J85', 'Vencedor J88', 'Vencedor J85', 'Vencedor J88', '2026-07-07T22:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null),
  ('quarterfinal-1', 97, 'quarterfinal', 'Quartas de final', null, 'Vencedor J89', 'Vencedor J90', 'Vencedor J89', 'Vencedor J90', '2026-07-09T22:00:00Z', 'Estádio de Los Angeles', 'Los Angeles', 'scheduled', null, null, null, null, null),
  ('quarterfinal-2', 98, 'quarterfinal', 'Quartas de final', null, 'Vencedor J91', 'Vencedor J92', 'Vencedor J91', 'Vencedor J92', '2026-07-10T22:00:00Z', 'Estádio de Kansas City', 'Kansas City', 'scheduled', null, null, null, null, null),
  ('quarterfinal-3', 99, 'quarterfinal', 'Quartas de final', null, 'Vencedor J93', 'Vencedor J94', 'Vencedor J93', 'Vencedor J94', '2026-07-11T18:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('quarterfinal-4', 100, 'quarterfinal', 'Quartas de final', null, 'Vencedor J95', 'Vencedor J96', 'Vencedor J95', 'Vencedor J96', '2026-07-11T22:00:00Z', 'Estádio de Boston', 'Boston', 'scheduled', null, null, null, null, null),
  ('semifinal-1', 101, 'semifinal', 'Semifinal', null, 'Vencedor J97', 'Vencedor J98', 'Vencedor J97', 'Vencedor J98', '2026-07-14T22:00:00Z', 'Estádio de Dallas', 'Dallas', 'scheduled', null, null, null, null, null),
  ('semifinal-2', 102, 'semifinal', 'Semifinal', null, 'Vencedor J99', 'Vencedor J100', 'Vencedor J99', 'Vencedor J100', '2026-07-15T22:00:00Z', 'Estádio de Atlanta', 'Atlanta', 'scheduled', null, null, null, null, null),
  ('third-place-1', 103, 'third-place', '3º lugar', null, 'Perdedor da Semifinal 1', 'Perdedor da Semifinal 2', 'Perdedor da Semifinal 1', 'Perdedor da Semifinal 2', '2026-07-18T20:00:00Z', 'Estádio de Miami', 'Miami', 'scheduled', null, null, null, null, null),
  ('final-1', 104, 'final', 'Final', null, 'Vencedor da Semifinal 1', 'Vencedor da Semifinal 2', 'Vencedor da Semifinal 1', 'Vencedor da Semifinal 2', '2026-07-19T19:00:00Z', 'Estádio New York New Jersey', 'Nova York / Nova Jersey', 'scheduled', null, null, null, null, null)
on conflict (id) do update set
  match_number = excluded.match_number,
  phase = excluded.phase,
  phase_label = excluded.phase_label,
  group_name = excluded.group_name,
  home_team = excluded.home_team,
  away_team = excluded.away_team,
  home_code = excluded.home_code,
  away_code = excluded.away_code,
  starts_at = excluded.starts_at,
  stadium = excluded.stadium,
  location = excluded.location,
  status = excluded.status,
  score_home = excluded.score_home,
  score_away = excluded.score_away,
  extra_time_home = excluded.extra_time_home,
  extra_time_away = excluded.extra_time_away,
  winner_team = excluded.winner_team,
  updated_at = now();

delete from predictions;
delete from bonus_predictions;
delete from chat_messages;
delete from app_sessions;